// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartPaster
{
    internal sealed partial class Vsix
    {
        public const string Id = "SmartPaster22.13ba9e2a-536c-41aa-8edc-1e3c0b6c59a2";
        public const string Name = "SmartPaster 64bit";
        public const string Description = @"Paste clipboard into comments or strings in C#, VB, C++";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Martin Willey";
        public const string Tags = "PasteAs Verbatim StringBuilder Comment Paste";
    }
}
