// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmartPaster
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SmartPaster22String = "1912cb07-6276-40a1-a4c3-7b01d96d912e";
        public static Guid SmartPaster22 = new Guid(SmartPaster22String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenu = 0x1022;
        public const int SubMenu = 0x1023;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidPasteAsComment = 0x0100;
        public const int cmdidPasteAsString = 0x0101;
        public const int cmdidPasteAsVerbatimString = 0x0102;
        public const int cmdidPasteAsStringBuilder = 0x0103;
        public const int cmdidPasteAsBytes = 0x0104;
        public const int cmdidPasteWithReplace = 0x0105;
        public const int cmdidPasteAsRaw = 0x0106;
    }
}